name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21458.32
    - name: Install maui-windows workload
      run: dotnet workload install maui-windows
    - name: Install ios workload
      run: dotnet workload install ios
    - name: Install android workload
      run: dotnet workload install android
    - name: Install maccatalyst workload
      run: dotnet workload install maccatalyst
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
