name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            workloads: 'ios android maccatalyst'
            build-args: ''
          - os: windows-latest
            workloads: 'android maui-windows'
            build-args: ''
          - os: ubuntu-latest
            workloads: 'android maui-tizen'
            build-args: ''
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install MAUI workloads
      run: |
        dotnet workload install ${{ matrix.workloads }}
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ${{ matrix.build-args }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
